<?php
include("../_inc/_app.php");
$app = new MyApp;
include("../_inc/_functions.php");
include("../_inc/header.php");
?>

<body id="flat">
<?php include("../_inc/navigation.php"); ?>

<main id="main">
	<div class="colors colors-flat">
	<div class="flat" style="background:#F9EAE9"></div>
	<div class="flat" style="background:#FDEDEB"></div>
	<div class="flat" style="background:#F5EEF8"></div>
	<div class="flat" style="background:#F4EBF7"></div>
	<div class="flat" style="background:#E9F2F7"></div>
	<div class="flat" style="background:#EBF5FB"></div>
	<div class="flat" style="background:#E8F7F5"></div>
	<div class="flat" style="background:#E8F6F3"></div>
	<div class="flat" style="background:#EAF6EF"></div>
	<div class="flat" style="background:#EAF9F1"></div>
	<div class="flat" style="background:#FEF9E7"></div>
	<div class="flat" style="background:#FDF5E7"></div>
	<div class="flat" style="background:#FDF2E9"></div>
	<div class="flat" style="background:#FBEEE6"></div>
	<div class="flat" style="background:#FDFEFE"></div>
	<div class="flat" style="background:#F8F9F9"></div>
	<div class="flat" style="background:#F3F6F6"></div>
	<div class="flat" style="background:#F1F4F4"></div>
	<div class="flat" style="background:#EAEDEF"></div>
	<div class="flat" style="background:#E9ECEE"></div>
	<div class="flat" style="background:#F2D7D5"></div>
	<div class="flat" style="background:#FADBD8"></div>
	<div class="flat" style="background:#EBDEF0"></div>
	<div class="flat" style="background:#E8DAEE"></div>
	<div class="flat" style="background:#D3E6F1"></div>
	<div class="flat" style="background:#D6EAF8"></div>
	<div class="flat" style="background:#D0F2EB"></div>
	<div class="flat" style="background:#CFECE7"></div>
	<div class="flat" style="background:#D4EFDF"></div>
	<div class="flat" style="background:#D5F5E3"></div>
	<div class="flat" style="background:#FBF3CF"></div>
	<div class="flat" style="background:#FDEBD0"></div>
	<div class="flat" style="background:#F9E5D3"></div>
	<div class="flat" style="background:#F6DDCC"></div>
	<div class="flat" style="background:#FBFCFC"></div>
	<div class="flat" style="background:#F2F3F4"></div>
	<div class="flat" style="background:#EAEDED"></div>
	<div class="flat" style="background:#E5E8E8"></div>
	<div class="flat" style="background:#D6DBDF"></div>
	<div class="flat" style="background:#D5D8DC"></div>
	<div class="flat" style="background:#E6B0AA"></div>
	<div class="flat" style="background:#F5B6B1"></div>
	<div class="flat" style="background:#D7BCE1"></div>
	<div class="flat" style="background:#D2B4DE"></div>
	<div class="flat" style="background:#A9CCE3"></div>
	<div class="flat" style="background:#AED6F1"></div>
	<div class="flat" style="background:#A3E4D7"></div>
	<div class="flat" style="background:#A2D9CE"></div>
	<div class="flat" style="background:#A9DFBE"></div>
	<div class="flat" style="background:#AAEBC6"></div>
	<div class="flat" style="background:#F9E79F"></div>
	<div class="flat" style="background:#F9D7A0"></div>
	<div class="flat" style="background:#F5CBA7"></div>
	<div class="flat" style="background:#EDBB99"></div>
	<div class="flat" style="background:#F6F9F9"></div>
	<div class="flat" style="background:#E4E7E9"></div>
	<div class="flat" style="background:#D5DBDB"></div>
	<div class="flat" style="background:#CCD1D1"></div>
	<div class="flat" style="background:#ADB6BF"></div>
	<div class="flat" style="background:#ABB2B9"></div>
	<div class="flat" style="background:#D98880"></div>
	<div class="flat" style="background:#F19489"></div>
	<div class="flat" style="background:#C39BD2"></div>
	<div class="flat" style="background:#BB8FCE"></div>
	<div class="flat" style="background:#7FB3D5"></div>
	<div class="flat" style="background:#85C1E9"></div>
	<div class="flat" style="background:#76D7C3"></div>
	<div class="flat" style="background:#73C6B5"></div>
	<div class="flat" style="background:#7DCE9F"></div>
	<div class="flat" style="background:#81E0AA"></div>
	<div class="flat" style="background:#F7DC6F"></div>
	<div class="flat" style="background:#F8C370"></div>
	<div class="flat" style="background:#F0B27A"></div>
	<div class="flat" style="background:#E59865"></div>
	<div class="flat" style="background:#F3F6F7"></div>
	<div class="flat" style="background:#D7DBDD"></div>
	<div class="flat" style="background:#BFC9CA"></div>
	<div class="flat" style="background:#B1BABB"></div>
	<div class="flat" style="background:#84929E"></div>
	<div class="flat" style="background:#808B96"></div>
	<div class="flat" style="background:#CC6155"></div>
	<div class="flat" style="background:#EC7062"></div>
	<div class="flat" style="background:#AF7AC4"></div>
	<div class="flat" style="background:#A569BD"></div>
	<div class="flat" style="background:#5599C7"></div>
	<div class="flat" style="background:#5CADE2"></div>
	<div class="flat" style="background:#48C9B0"></div>
	<div class="flat" style="background:#44B29D"></div>
	<div class="flat" style="background:#53BE80"></div>
	<div class="flat" style="background:#57D68C"></div>
	<div class="flat" style="background:#F4CF40"></div>
	<div class="flat" style="background:#F5B041"></div>
	<div class="flat" style="background:#EB984E"></div>
	<div class="flat" style="background:#DC7633"></div>
	<div class="flat" style="background:#F0F3F4"></div>
	<div class="flat" style="background:#CACFD2"></div>
	<div class="flat" style="background:#A9B7B8"></div>
	<div class="flat" style="background:#99A3A4"></div>
	<div class="flat" style="background:#5D6D7D"></div>
	<div class="flat" style="background:#566573"></div>
	<div class="flat" style="background:#BF392B"></div>
	<div class="flat" style="background:#E74C3C"></div>
	<div class="flat" style="background:#9B59B6"></div>
	<div class="flat" style="background:#8D44AD"></div>
	<div class="flat" style="background:#2980B9"></div>
	<div class="flat" style="background:#3398DA"></div>
	<div class="flat" style="background:#1ABC9B"></div>
	<div class="flat" style="background:#169F85"></div>
	<div class="flat" style="background:#26AE60"></div>
	<div class="flat" style="background:#2FCB71"></div>
	<div class="flat" style="background:#F1C40F"></div>
	<div class="flat" style="background:#F39C13"></div>
	<div class="flat" style="background:#E57E23"></div>
	<div class="flat" style="background:#D35400"></div>
	<div class="flat" style="background:#ECF0F1"></div>
	<div class="flat" style="background:#BDC3C7"></div>
	<div class="flat" style="background:#95A5A6"></div>
	<div class="flat" style="background:#7E8C8D"></div>
	<div class="flat" style="background:#33495E"></div>
	<div class="flat" style="background:#2C3E4F"></div>
	<div class="flat" style="background:#A93225"></div>
	<div class="flat" style="background:#CB4335"></div>
	<div class="flat" style="background:#884E9F"></div>
	<div class="flat" style="background:#7D3C98"></div>
	<div class="flat" style="background:#2571A3"></div>
	<div class="flat" style="background:#2F86C1"></div>
	<div class="flat" style="background:#19A589"></div>
	<div class="flat" style="background:#138D75"></div>
	<div class="flat" style="background:#239954"></div>
	<div class="flat" style="background:#27B463"></div>
	 <div class="flat" style="background:#D68910"></div>
	<div class="flat" style="background:#CA6F1D"></div>
	<div class="flat" style="background:#AF5F1A"></div>
	<div class="flat" style="background:#BA4A01"></div>
	<div class="flat" style="background:#D0D3D4"></div>
	<div class="flat" style="background:#A6ACAF"></div>
	<div class="flat" style="background:#839192"></div>
	<div class="flat" style="background:#707B7C"></div>
	<div class="flat" style="background:#2E4053"></div>
	<div class="flat" style="background:#273746"></div>
	<div class="flat" style="background:#922B21"></div>
	<div class="flat" style="background:#B03A2E"></div>
	<div class="flat" style="background:#76438A"></div>
	<div class="flat" style="background:#6C3383"></div>
	<div class="flat" style="background:#1F618D"></div>
	<div class="flat" style="background:#2874A6"></div>
	<div class="flat" style="background:#148F77"></div>
	<div class="flat" style="background:#127A65"></div>
	<div class="flat" style="background:#1D8449"></div>
	<div class="flat" style="background:#249B56"></div>
	<div class="flat" style="background:#B7950B"></div>
	<div class="flat" style="background:#B9770D"></div>
	<div class="flat" style="background:#AF5F1A"></div>
	<div class="flat" style="background:#A04000"></div>
	<div class="flat" style="background:#B3B6B7"></div>
	<div class="flat" style="background:#909497"></div>
	<div class="flat" style="background:#717D7E"></div>
	<div class="flat" style="background:#616A6B"></div>
	<div class="flat" style="background:#283747"></div>
	<div class="flat" style="background:#212F3D"></div>
	<div class="flat" style="background:#7A241C"></div>
	<div class="flat" style="background:#943126"></div>
	<div class="flat" style="background:#633974"></div>
	<div class="flat" style="background:#5B2C6E"></div>
	<div class="flat" style="background:#1A5276"></div>
	<div class="flat" style="background:#21618C"></div>
	<div class="flat" style="background:#127864"></div>
	<div class="flat" style="background:#0F6655"></div>
	<div class="flat" style="background:#186F3D"></div>
	<div class="flat" style="background:#1B8348"></div>
	<div class="flat" style="background:#997C0B"></div>
	<div class="flat" style="background:#9C640D"></div>
	<div class="flat" style="background:#935116"></div>
	<div class="flat" style="background:#873601"></div>
	<div class="flat" style="background:#979A9A"></div>
	<div class="flat" style="background:#797D7F"></div>
	<div class="flat" style="background:#5F6A6A"></div>
	<div class="flat" style="background:#515A5A"></div>
	<div class="flat" style="background:#212F3C"></div>
	<div class="flat" style="background:#1B2833"></div>
	<div class="flat" style="background:#641E16"></div>
	<div class="flat" style="background:#782820"></div>
	<div class="flat" style="background:#512E5F"></div>
	<div class="flat" style="background:#4A235A"></div>
	<div class="flat" style="background:#154361"></div>
	<div class="flat" style="background:#1C4F72"></div>
	<div class="flat" style="background:#0E6251"></div>
	<div class="flat" style="background:#095345"></div>
	<div class="flat" style="background:#155A32"></div>
	<div class="flat" style="background:#186A3A"></div>
	<div class="flat" style="background:#7D6608"></div>
	<div class="flat" style="background:#7E510A"></div>
	<div class="flat" style="background:#784213"></div>
	<div class="flat" style="background:#6E2C00"></div>
	<div class="flat" style="background:#7A7D7D"></div>
	<div class="flat" style="background:#626567"></div>
	<div class="flat" style="background:#4D5656"></div>
	<div class="flat" style="background:#424949"></div>
	<div class="flat" style="background:#1B2631"></div>
	<div class="flat" style="background:#17202A"></div>
	</div>
</main>

<?php include("../_inc/scripts.php"); ?>
<?php include("../_inc/footer.php"); ?>

